#! /usr/bin/env bash

{

has_cmd() {
    command -v "$1" > /dev/null
}

chrome_install() {
  has_cmd google-chrome && return 1

  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb


  sudo dpkg -i google-chrome-stable_current_amd64.deb

  # Install any missing dependencies using apt-get
  sudo apt-get -f install

  rm -f google-chrome-stable_current_amd64.deb
}

curdir=$(pwd)

rm -f ~/.seartipy-error.log ~/.seartipy-output.log 2> /dev/null
installer > >(tee ~/.seartipy-output.log) 2> >(tee ~/.seartipy-error.log >&2)

cd "$curdir"

}
