#! /usr/bin/env bash

{

docker_install() {
    curl -fsSL https://get.docker.com | sh -s -- -y
    sudo apt-get install -y uidmap
    dockerd-rootless-setuptool.sh install
    sudo loginctl enable-linger pervez
}


installer() {
    docker_install
}

export PATH=/usr/bin:$PATH

echo "Installing Docker..."
rm -f ~/.seartipy-error.log ~/.seartipy-output.log 2> /dev/null
installer > >(tee ~/.seartipy-output.log) 2> >(tee ~/.seartipy-error.log >&2)

}
