#! /usr/bin/env bash

{

docker_install() {
    curl -fsSL https://get.docker.com | sh -s -- -y
}

installer() {
    docker_install
}

rm -f ~/.seartipy-error.log ~/.seartipy-output.log 2> /dev/null
installer > >(tee ~/.seartipy-output.log) 2> >(tee ~/.seartipy-error.log >&2)

}
