#! /usr/bin/env bash

{


dotnet_install() {
    has_cmd dotnet && return 0

    wget https://packages.microsoft.com/config/ubuntu/22.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb
    sudo apt-get update
    sudo apt-get install -y dotnet-sdk-7.0
}

installer() {
    dotnet_install
}

export DOTNET_ROOT=$HOME/.dotnet

echo "Installing .NET 7.0..."
rm -f ~/.seartipy-error.log ~/.seartipy-output.log 2> /dev/null
installer > >(tee ~/.seartipy-output.log) 2> >(tee ~/.seartipy-error.log >&2)

}
