#! /usr/bin/env bash

{

has_cmd() {
  command -v "$1" > /dev/null
}

flathub_install() {
  if has_cmd apt; then
    sudo apt-get install -y flatpak gnome-software-plugin-flatpak
  fi

  has_cmd flatpak && flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
}

browsers_install() {
  has_cmd edge-browser && return 0
  flathub_install

  flatpak install flathub com.microsoft.Edge -y
  flatpak install flathub com.google.Chrome -y
}

installer() {
  browsers_install
}

export PATH="$HOME/bin:$PATH"

export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

echo "Installing chrome and edge browsers via flatpak..."
rm -f ~/.seartipy-error.log ~/.seartipy-output.log 2> /dev/null
installer > >(tee ~/.seartipy-output.log) 2> >(tee ~/.seartipy-error.log >&2)
}
