#! /usr/bin/env bash

{

has_cmd() {
    command -v "$1" > /dev/null
}

pnpm_install() {
    has_cmd pnpm && return 0

    echo "Installing node"
    curl -fsSL https://get.pnpm.io/install.sh | sh -

    pnpm env use --global latest

    export PNPM_HOME="$HOME/.local/share/pnpm"
    export PATH="$PNPM_HOME:$PATH"

    pnpm install-completion bash
    pnpm install-completion zsh
}

installer() {
    pnpm_install

    echo "Installign npm packages"
    pnpm install -g npm-check-updates degit tldr gtop

    if ! grep "fs.inotify.max_user_watches" /etc/sysctl.conf > /dev/null; then
        echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf > /dev/null && sudo sysctl -p
    fi
}

export PATH="$HOME/bin:$PATH"

export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

curdir=$(pwd)
rm -f  ~/seartipy-error.log ~/seartipy-output.log 2> /dev/null
installer > >(tee ~/seartipy-output.log) 2> >(tee ~/seartipy-error.log >&2)
cd "$curdir"

}
