#! /usr/bin/env bash

{

has_cmd() {
    command -v "$1" > /dev/null
}

vscode_install() {
    has_cmd code && return 0

    has_cmd snap || err_exit "snap not installed. Can't install vscode."

    echo "Installing visual studio code"
    sudo snap install --classic code
}

flathub_install() {
    if has_cmd apt; then
    sudo apt-get install -y flatpak gnome-software-plugin-flatpak
  fi

  has_cmd flatpak && flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
}

browsers_install() {
  has_cmd edge-browser && return 0
  flathub_install()

  flatpak install flathub com.microsoft.Edge
  flatpak install flathub com.google.Chrome

}

installer() {
    vscode_install
    browsers_install

    echo "Installing npm packages"
    has_cmd pnpm && pnpm install -g npm-check-updates degit tldr gtop

}

export PATH="$HOME/bin:$PATH"

export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

curdir=$(pwd)

rm -f ~/.seartipy-error.log ~/.seartipy-output.log 2> /dev/null
installer > >(tee ~/.seartipy-output.log) 2> >(tee ~/.seartipy-error.log >&2)

cd "$curdir"

}
