#! /usr/bin/env bash

{

has_cmd() {
    command -v "$1" > /dev/null
}

emacs_install() {
  git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
  mv ~/.config/doom ~/.config/doom.backup
  sclone https://github.com/pervezfunctor/doomemacs-config ~/.config/doom

  has_cmd update-locale && sudo update-locale LANG=en_US.UTF8

  if has_cmd apt-get; then
    sudo apt-get install -y emacs-nox
  elif has_cmd dnf; then
    sudo dnf install -y emacs-nox
  else
    err_exit "emacs can't be installed: unknown os"
  fi
}

main() {
    emacs_install
}

echo "Installing emacs..."
rm -f ~/.seartipy-error.log ~/.seartipy-output.log 2> /dev/null
installer > >(tee ~/.seartipy-output.log) 2> >(tee ~/.seartipy-error.log >&2)
echo "Installing emacs done."
}
