#! /usr/bin/env bash

{

DOT_DIR=~/.config/mini-seartipy

# utils

slog() {
    echo "
${BOLD}${GREEN}SEARTIPY: ${RESET} $1
"
}

err_exit() {
    echo "
${BOLD}${RED}FATAL: ${RESET} $1
"
    exit 1
}

has_cmd() {
    command -v "$1" > /dev/null
}

is_fedora() {
    grep 'Fedora' /etc/redhat-release > /dev/null || grep 'Rocky' /etc/redhat-release > /dev/null || grep 'Centos' /etc/redhat-release > /dev/null
}

sclone() {
    local dest=${*: -1}
    local src=${*: -2:1}

    [ -d "$dest" ] && return 1

    slog "Cloning $src to $dest"
    git clone "$@"
}

smd() {
    [ -d "$1" ] && return 1

    slog "Creating directory $1"
    smd "$1" 2> /dev/null
}

fln() {
    if [ -e "$1" ]; then
        rm -f "$2"
    else
        echo "$1 does not exist, cannot create link $2"
        return 1
    fi
    slog "Creating link $2 to $1"
    ln -s "$1" "$2"
}

# essential

dnfi() {
    for p in "$@"; do
    slog "Installing package $p"
        sudo dnf -y install "$p"
    done
}

# ssh_install() {
#     slog "Installing ssh"

#     sudo dnf install openssh-server -y

#     slog "Starting sshd"
#     sudo systemctl start sshd
#     sudo systemctl enable sshd

#     slog "Setting up firewall"
#     sudo dnf install firewalld -y
#     sudo systemctl start firewalld
#     sudo systemctl enable firewalld

#     sudo firewall-cmd --permanent --add-service=ssh
#     sudo firewall-cmd --reload

#     # allow root to ssh

# }

essential_install() {
    slog "Updating fedora"

    if ! { sudo dnf update -y && sudo dnf upgrade -y; }; then
        err_exit "dnf update/upgrade failed, quitting"
    fi

    slog "Installing essential fedora packages"

    dnfi install epel-release
    dnfi curl wget git trash-cli tree fzf ripgrep
    dnfi tmux pkg-config urlview micro
    dnfi zsh zsh-syntax-highlighting zsh-autosuggestions fd-find
    dnfi neovim

    dnfi unar unzip p7zip zoxide gh
    dnfi ShellCheck git-extras zip gawk

    has_cmd gh && gh extension install github/gh-copilot
    slog "Setting up snapd"
    dnfi snapd

    [ -e /snap ] || sudo ln -s /var/lib/snapd/snap /snap
    sudo snap install fasd --beta
}

dotfiles_install() {
    sclone https://github.com/pervezfunctor/mini-dotfiles.git "${DOT_DIR}"
}

micro_install() {
    has_cmd micro && return 1

    slog "Installing micro"

    dnfi install curl tar -y
    curl https://getmic.ro | bash
    sudo mv micro /usr/bin/
}

cpp_install() {
    sudo dnf groupinstall "Development Tools" -y
    sudo dnf groupinstall -y "C Development Tools and Libraries"
    dnfi cmake gcc-c++ clang llvm boost clang-tools-extra pre-commit
}

# zsh

zsh_install() {
    slog "Installing zsh"

    smd ~/.zsh
    sclone --depth=1 https://github.com/sindresorhus/pure.git ~/.zsh/pure
    sclone --depth=1 https://github.com/djui/alias-tips.git ~/.zsh/alias-tips

    fln "${DOT_DIR}/configs/zshrc" ~/.zshrc
}

installer() {
    essential_install
    dotfiles_install
    micro_install
    zsh_install
    cpp_install

    echo "Set zsh as default"
    sudo chsh -s $(which zsh) $(whoami)

    slog "Installation done! Look at ~/.seartipy-error.log for any errors."
}

keep_sudo_running() {
    sudo -v
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
}

is_fedora || err_exit "This installer works only on Fedora. Quitting."

curdir=$(pwd)

rm -f ~/.seartipy-error.log ~/.seartipy-output.log 2> /dev/null

slog "Installing..."

keep_sudo_running

smd ~/bin
export PATH="$HOME/bin:$PATH"
export DEBIAN_FRONTEND=noninteractive

installer > >(tee ~/.seartipy-output.log) 2> >(tee ~/.seartipy-error.log >&2)

cd "$curdir"

}
