#! /usr/bin/env bash

{

DOT_DIR=~/.config/mini-seartipy

# utils

slog() {
    echo "
${BOLD}${GREEN}SEARTIPY: ${RESET} $1
"
}

err_exit() {
    echo "
${BOLD}${RED}FATAL: ${RESET} $1
"
    exit 1
}

has_cmd() {
    command -v "$1" > /dev/null
}

is_fedora() {
    grep 'Fedora' /etc/redhat-release > /dev/null
}

sclone() {
    local dest=${*: -1}
    local src=${*: -2:1}

    [ -d "$dest" ] && return 1

    slog "Cloning $src to $dest"
    git clone "$@"
}

smd() {
    [ -d "$1" ] && return 1

    slog "Creating directory $1"
    mkdir -p "$1" 2> /dev/null
}

fln() {
    if [ -e "$1" ]; then
        rm -f "$2"
    else
        echo "$1 does not exist, cannot create link $2"
        return 1
    fi
    slog "Creating link $2 to $1"
    ln -s "$1" "$2"
}

# essential

dnfi() {
    for p in "$@"; do
    slog "Installing package $p"
        sudo dnf -y install "$p"
    done
}

essential_install() {
    slog "Updating fedora"

    if ! { sudo dnf update -y && sudo dnf upgrade -y; }; then
        err_exit "dnf update/upgrade failed, quitting"
    fi

    slog "Installing essential fedora packages"
    dnfi curl wget git trash-cli tree fzf ripgrep
    dnfi tmux pkg-config urlview cascadia-fonts-all jetbrains-mono-fonts-all micro
    dnfi zsh zsh-syntax-highlighting zsh-autosuggestions fd-find

    dnfi unar unzip p7zip zoxide gh
    dnfi ShellCheck git-extras zip gawk

    slog "Setting up snapd"
    dnfi snapd

    [ -e /snap ] || sudo ln -s /var/lib/snapd/snap /snap
    sudo snap install fasd --beta
}

dotfiles_install() {
    sclone https://github.com/pervezfunctor/mini-dotfiles.git "${DOT_DIR}"
}

cockpit_install() {
    dnfi install cockpit
    sudo systemctl enable --now cockpit.socket
    sudo firewall-cmd --add-service=cockpit
    sudo firewall-cmd --add-service=cockpit --permanent
}

docker_install() {
    has_cmd docker && return 1

    slog "Installing docker"
    dnfi dnf-plugins-core
    sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    dnfi docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    sudo systemctl start docker

    slog "Setting up docker user group"
    sudo groupadd docker
    sudo usermod -aG docker $USER

    slog "Setting up docker service"
    sudo systemctl enable docker.service
    sudo systemctl enable containerd.service
}

sys_install() {
    sudo dnf ininstall -y toolbox buildah distrobox
    sudo dnf groupinstall -y --with-optional "virtualization"
    sudo systemctl start libvirtd
    sudo systemctl enable libvirtd

    sudo dnf groupinstall -y --with-optional "System Tools"
}

lxd_install() {
    has_cmd lxd && return 1
    slog "Installing lxd"

    sudo snap install lxd

    slog "Setting up lxd service"
    sudo snap enable lxd
    sudo snap services lxd

    slog "Setting up lxd user group"
    sudo usermod -a -G lxd $USER
    id $USER
flk
    slog "lxd installation done! Start using it right now with `newgrp lxd`, followed by `lxd init`"
}

code_install() {
    has_cmd code && return 1

    sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
    dnf check-update
    dnfi code code-insiders
}

flathub_install() {
    has_cmd flatpak || return 1
    flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo --user
}

cpp_install() {
    sudo dnf groupinstall -y "Development Tools"
    sudo dnf groupinstall -y "C Development Tools and Libraries"
    dnfi cmake gcc-c++ clang llvm boost clang-tools-extra pre-commit
}

apps_install() {
    dnfi virt-manager chromium neovim emacs
    # flatpak install -y --user flathub com.visualstudio.code
    flatpak install -y --user flathub org.telegram.desktop
    flatpak install -y --user flathub com.jetbrains.CLion
    flatpak install -y --user flathub com.google.Chrome
    flatpak install -y --user flathub org.deluge_torrent.deluge
    flatpak install -y --user flathub us.zoom.Zoom
}

monaspace_install() {
    wget https://github.com/githubnext/monaspace/releases/download/v1.000/monaspace-v1.000.zip
    unzip -d monaspace monaspace-v1.000.zip
    smd ~/.local/share/fonts
    # TODO: Don't copy if already exists
    cp ./monaspace/monaspace-v1.000/fonts/otf/* ~/.local/share/fonts
    cp ./monaspace/monaspace-v1.000/fonts/variable/* ~/.local/share/fonts
    trash monaspace monaspace-v1.000.zip
}

# zsh

zsh_install() {
    slog "Installing zsh"

    smd ~/.zsh
    sclone --depth=1 https://github.com/sindresorhus/pure.git ~/.zsh/pure
    sclone --depth=1 https://github.com/djui/alias-tips.git ~/.zsh/alias-tips

    fln "${DOT_DIR}/configs/zshrc" ~/.zshrc
}

installer() {
    essential_install
    flathub_install
    dotfiles_install
    zsh_install
    docker_install
    lxd_install
    cpp_install
    monaspace_install
    code_install
    sys_install
    apps_install

    echo "Set zsh as default"
    sudo chsh -s $(which zsh) $(whoami)

    slog "Installation done!"
}

keep_sudo_running() {
    sudo -v
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
}

is_fedora || err_exit "This installer works only on Fedora. Quitting."

curdir=$(pwd)

rm -f ~/.seartipy-error.log ~/.seartipy-output.log 2> /dev/null

slog "Installing..."

keep_sudo_running

smd ~/bin
export PATH="$HOME/bin:$PATH"
export DEBIAN_FRONTEND=noninteractive

installer > >(tee ~/.seartipy-output.log) 2> >(tee ~/.seartipy-error.log >&2)

cd "$curdir"

}
