#! /usr/bin/env bash

{

source <(curl -s https://raw.githubusercontent.com/pervezfunctor/mini-dotfiles/master/scripts/utils)

sys_install() {
    sudo dnf groupinstall -y --with-optional "virtualization"
    sudo dnf groupinstall -y --with-optional "System Tools"

    dnfi toolbox buildah distrobox

    sudo systemctl start libvirtd
    sudo systemctl enable libvirtd
}

cpp_fedora_install() {
    slog "Installing C++ tools"

    cpp_install
    sudo dnf groupinstall -y --with-optional "C Development Tools and Libraries"

    slog "C++ tools installation done!"
}

flatpak_apps_install() {
    # flatpak install -y --user flathub com.visualstudio.code
    flatpak install -y --user flathub org.telegram.desktop
    flatpak install -y --user flathub com.jetbrains.CLion
    flatpak install -y --user flathub com.google.Chrome
    flatpak install -y --user flathub org.deluge_torrent.deluge
    flatpak install -y --user flathub us.zoom.Zoom
}

apps_install() {
    dnfi virt-manager chromium neovim emacs
    flatpak_apps_install
}

main() {
    essential_install
    dnfi micro

    flathub_install
    snap_install

    dotfiles_install

    zsh_install
    docker_install
    lxd_install
    cpp_fedora_install
    fonts_install
    vscode_install
    sys_install
    apps_install

    set_zsh_as_default
}

is_fedora || err_exit "This script works only on Fedora. Quitting."

bootstrap "Fedora desktop setup"

}
