#! /usr/bin/env bash

{

source <(curl -fsSL https://raw.githubusercontent.com/pervezfunctor/mini-dotfiles/master/scripts/utils)

main() {
    dotfiles_install

    essential_core_install
    # sudo dnf install -y qemu-guest-agent

    cpp_install
    docker_install
    cockpit_install
    gh_install
    lazygit_install
    gdu_install
    bottom_install

    micro_install
    zsh_install
    code_server_install
    pnpm_install
    astro_install

    set_zsh_as_default
}

is_rocky|| err_exit "This installer works only on Rocky Linux. Quitting."

bootstrap "Rocky Linux development system"

}
