#! /usr/bin/env bash

{

source <(curl -fsSL https://raw.githubusercontent.com/pervezfunctor/mini-dotfiles/master/scripts/utils)

cockpit_install() {
    apti cockpit
}

main() {
    dotfiles_install

    essential_install

    cpp_install
    docker_install

    apti cockpit gh gdu micro

    go_install

    go install github.com/jesseduffield/lazygit@latest
    # bottom_install

    zsh_install
    code_server_install
    pnpm_install

    neovim_debian_install
    astro_install

    set_zsh_as_default
}

is_debian || err_exit "This installer works only on Debian. Quitting."

bootstrap "Debian development system"

}
