#! /usr/bin/env bash

{

source <(curl -fsSL https://raw.githubusercontent.com/pervezfunctor/mini-dotfiles/master/scripts/utils)

main() {
  docker_setup
}

is_apt || err_exit "This installer works only on Ubuntu or Debian. Quitting."

export DEBIAN_FRONTEND=noninteractive

installer "Docker"

}
