#! /usr/bin/env bash

{

source <(curl -fsSL https://raw.githubusercontent.com/pervezfunctor/mini-dotfiles/master/scripts/utils)

main() {
    essential_install
    dotfiles_install

    zsh_install

    set_zsh_as_default

    sudo apt-get autoremove -y
    slog "Installation done!"
}

is_apt || err_exit "This installer works only on Ubuntu or Debian. Quitting."

export DEBIAN_FRONTEND=noninteractive

bootstrap "Ubuntu/Debian setup"

}
