#! /usr/bin/env bash

{

source <(curl -fsSL https://raw.githubusercontent.com/pervezfunctor/mini-dotfiles/master/scripts/utils)

main() {
    while [[ "$#" -gt 0 ]]; do
    if fn_exists "${1}_install"; then
        "${1}_install"
    fi
    shift
    done
}

bootstrap "seartipy setup"

}
