#! /usr/bin/env bash

{

source bash -c "$(curl -fsSL https://raw.githubusercontent.com/pervezfunctor/mini-seartipy/master/portable/utils)"

installer() {
    has_cmd brew && return 0
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

install "homebrew"

}
