#! /usr/bin/env bash

{

source bash -c "$(curl -fsSL https://raw.githubusercontent.com/pervezfunctor/mini-seartipy/master/portable/utils)"

dotfiles_install() {
    sclone https://github.com/pervezfunctor/mini-dotfiles.git "${DOT_DIR}"
}

zsh_install() {
    slog "Installing zsh"

    smd ~/.zsh
    sclone --depth=1 https://github.com/sindresorhus/pure.git ~/.zsh/pure
    sclone --depth=1 https://github.com/djui/alias-tips.git ~/.zsh/alias-tips

    fln "${DOT_DIR}/configs/zshrc" ~/.zshrc

    slog "zsh installation done!"
}

installer() {
    dotfiles_install
    zsh_install
}

smd ~/bin
export PATH="$HOME/bin:$PATH"

install "dotfiles"

}
