#! /usr/bin/env bash

{


has_cmd() {
    command -v "$1" > /dev/null
}

miniconda_install() {
    has_cmd conda && return 0

    mkdir -p ~/miniconda3
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
    bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
    rm -rf ~/miniconda3/miniconda.sh
    ~/miniconda3/bin/conda init bash
    # ~/miniconda3/bin/conda init zsh
}

installer() {
    miniconda_install
}

echo "Installing miniconda..."
rm -f ~/.seartipy-error.log ~/.seartipy-output.log 2> /dev/null
installer > >(tee ~/.seartipy-output.log) 2> >(tee ~/.seartipy-error.log >&2)
echo "Installing miniconda done."

}
