#! /usr/bin/env bash

{

source bash -c "$(curl -fsSL https://raw.githubusercontent.com/pervezfunctor/mini-seartipy/master/portable/utils)"

pnpm_install() {
    # has_cmd pnpm && return 0

    echo "Installing pnpm"
    if has_cmd curl; then
        curl -fsSL https://get.pnpm.io/install.sh | sh -
    elif has_cmd wget; then
        wget -qO- https://get.pnpm.io/install.sh | sh -
    else
        echo "curl  or wget must be installed"
        return 1
    fi

    echo "Installing node"
    pnpm env use --global latest

    pnpm install-completion bash
    pnpm install-completion zsh

    if has_cmd apt; then
        pnpm dlx playwright install-deps
        pnpm dlx playwright install
    fi
}

installer() {
    pnpm_install

    echo "Installing npm packages globally"
    pnpm install -g npm-check-updates degit tldr gtop ndb @antfu/ni
    pnpm install -g tsx vite-node zx turbo
    pnpm install -g @githubnext/github-copilot-cli
    if ! grep "fs.inotify.max_user_watches" /etc/sysctl.conf > /dev/null; then
        echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf > /dev/null && sudo sysctl -p
    fi
}

export PATH="$HOME/bin:$PATH"

export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

install "pnpm"

}
