#! /usr/bin/env bash

{

source bash -c "$(curl -fsSL https://raw.githubusercontent.com/pervezfunctor/mini-seartipy/master/portable/utils)"

rust_install() {
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
}

installer() {
    rust_install
}

install "rust"

}
