#! /usr/bin/env bash

{

has_cmd() {
    command -v "$1" > /dev/null
}

docker_setup() {
  has_cmd docker && return 0

  sudo apt-get update

  # Install required packages
  sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common

  # Add Docker GPG key
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  # Add Docker repository to APT sources
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

  # Update the package list
  sudo apt-get update

  # Install Docker Engine
  sudo apt-get install -y docker-ce docker-ce-cli containerd.io

  # Install Docker Compose
  sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose

  # Add current user to docker group
  sudo usermod -aG docker ${USER}

  # Enable Docker to start on boot
  sudo systemctl enable docker.service
  sudo systemctl enable containerd.service
}

installer() {
  docker_setup
}

export PATH=/usr/bin:$PATH

echo "Installing Docker..."
rm -f ~/.seartipy-error.log ~/.seartipy-output.log 2> /dev/null
installer > >(tee ~/.seartipy-output.log) 2> >(tee ~/.seartipy-error.log >&2)

}
